// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerAPIMPwDB.Infrastructure.Persistence;

#nullable disable

namespace PokerAPIMPwDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212062028_AddisDeletedinUser")]
    partial class AddisDeletedinUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChipStack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.PlayerSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TableId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("TableId");

                    b.ToTable("PlayerSeats");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.HasOne("PokerAPIMPwDB.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.PlayerSeat", b =>
                {
                    b.HasOne("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Player", "Player")
                        .WithOne("PlayerSeat")
                        .HasForeignKey("PokerAPIMPwDB.Infrastructure.Persistence.Entities.PlayerSeat", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Table", "Table")
                        .WithMany("PlayerSeats")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Player", b =>
                {
                    b.Navigation("PlayerSeat");
                });

            modelBuilder.Entity("PokerAPIMPwDB.Infrastructure.Persistence.Entities.Table", b =>
                {
                    b.Navigation("PlayerSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
